<a href="https://colab.research.google.com/github/kanchichandu/SQL_queries/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql
SELECT *
FROM sales
LIMIT 15

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

15 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16
10,1004,2,2015-01-01,2015-01-01,254117,80,1633,1,8.33,8.33,3.83,CAD,1.16
11,1004,3,2015-01-01,2015-01-01,254117,80,450,1,2297.50,2067.75,761.20,CAD,1.16
12,1005,0,2015-01-01,2015-01-01,1160597,390,1303,10,152.00,152.00,69.90,GBP,0.64
13,1005,1,2015-01-01,2015-01-01,1160597,390,1705,2,4.82,4.82,2.21,GBP,0.64
14,1006,0,2015-01-01,2015-01-01,1895118,480,173,1,71.92,63.29,36.66,USD,1.00

In [3]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [4]:
%%sql
SELECT *
FROM currencyexchange
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [5]:
%%sql
SELECT *
FROM store
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [6]:
%%sql
SELECT *
FROM product
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [30]:
%%sql
SELECT *
FROM customer
WHERE continent = 'Europe'
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,407269,25,1989-08-30,2032-08-23,Europe,male,Mr.,Robert,A,Finkel,...,95517,DE,Germany,1976-10-21,44,Research chef,A+ Electronics,1995 Ford Probe,50.00,11.74
1,407270,25,1989-12-19,2037-07-31,Europe,male,Mr.,Jens,A,Mayer,...,86027,DE,Germany,1948-01-01,73,General superintendent,Realty Solution,2002 Infiniti FX,48.31,10.88
2,407293,33,1987-11-03,2041-05-18,Europe,female,Mrs.,Kristin,S,Bayer,...,24029,DE,Germany,1942-01-22,79,Usher,Del Farm,2007 Aston Martin DB9,54.30,10.10
3,452848,34,2002-03-25,2039-06-19,Europe,male,Mr.,Uwe,J,Wurfel,...,66399,DE,Germany,1977-08-15,43,Recruitment consultant,WWW Realty,2012 Toyota Matrix,49.16,7.19
4,452897,32,2009-04-14,2024-10-15,Europe,male,Mr.,Torsten,S,Roth,...,55131,DE,Germany,1973-04-10,47,Chemical equipment operator,Mages,1997 Dodge Sidewinder,49.92,8.25
5,400020,32,2007-05-08,2024-07-01,Europe,male,Mr.,Jan,Y,Wolf,...,54552,DE,Germany,1954-12-23,66,Copy marker,d.e.m.o.,2006 Maybach 57,50.29,6.78
6,400027,24,1983-07-06,2034-09-30,Europe,male,Mr.,Phillipp,S,Nadel,...,70191,DE,Germany,1994-09-19,26,Hospice nurse,County Market,2012 Daihatsu Cuore,48.71,9.16
7,400044,32,1996-06-15,2020-01-31,Europe,female,Ms.,Petra,S,Furst,...,55767,DE,Germany,1970-01-21,51,Local controller,Family Toy,2006 Mazda B2300,49.78,7.32
8,400054,24,1987-12-21,2022-11-03,Europe,female,Ms.,Nicole,F,Gersten,...,70565,DE,Germany,1939-11-16,81,Bonus clerk,Star Assistance,2008 Chrysler PT Cruiser,48.70,9.04
9,400058,30,1997-10-23,2043-12-31,Europe,female,Ms.,Diana,D,Zimmer,...,31637,DE,Germany,1972-09-19,48,Gas appliance repairer,Huffman and Boyle,2004 Mercury Grand Marquis,52.63,9.51

In [8]:
%%sql
SELECT *
FROM information_schema.columns
WHERE table_name = 'customer'

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [9]:
%%sql
SELECT *
FROM date
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [29]:
%%sql

SELECT
  s.orderdate,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  CASE WHEN s.quantity * s.netprice * s.exchangerate > 1000 THEN 'HIGH' ELSE 'LOW' END AS high_low
FROM sales s
LEFT JOIN customer c
  ON s.customerkey = c.customerkey
LEFT JOIN product p
  ON s.productkey = p.productkey
WHERE orderdate::date >= '2020-01-01'
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,LOW
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,LOW
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",LOW
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,HIGH
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,LOW
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,HIGH
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games,LOW
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,LOW
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,HIGH
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors,HIGH

In [28]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT s.customerkey) AS total_customers,
  COUNT(DISTINCT CASE WHEN c.continent ='Europe' THEN s.customerkey END) AS eu_customers
FROM sales s
LEFT JOIN customer c
  ON s.customerkey = c.customerkey
WHERE orderdate BETWEEN '2020-01-01' AND '2023-12-31'
GROUP BY
  s.orderdate
ORDER BY
  s.orderdate

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

1423 rows affected.

       orderdate  total_customers  eu_customers
0     2020-01-01               46            10
1     2020-01-02               52            20
2     2020-01-03               34             9
3     2020-01-04               62            16
4     2020-01-05                5             1
...          ...              ...           ...
1418  2023-12-27               73            26
1419  2023-12-28               75            24
1420  2023-12-29               55            19
1421  2023-12-30               91            25
1422  2023-12-31                9             1

[1423 rows x 3 columns]